"""initial

Revision ID: b1780eb594d6
Revises:
Create Date: 2026-09-17 23:46:08.923547

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1780eb594d6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrichment_cache",
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_excerpt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "regex_signals", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column(
            "llm_signals", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column(
            "contacts", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("robots_blocked", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("domain"),
    )
    with op.batch_alter_table("enrichment_cache", schema=None) as batch_op:
        batch_op.create_index("ix_enrichment_cache_expires", ["expires_at"], unique=False)

    op.create_table(
        "geocode_cache",
        sa.Column("query_norm", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "result", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("query_norm"),
    )
    op.create_table(
        "overpass_cache",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("overpass_cache", schema=None) as batch_op:
        batch_op.create_index("ix_overpass_cache_expires", ["expires_at"], unique=False)

    op.create_table(
        "searches",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("industry_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location_query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("geocoded_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bbox_s", sa.Float(), nullable=True),
        sa.Column("bbox_w", sa.Float(), nullable=True),
        sa.Column("bbox_n", sa.Float(), nullable=True),
        sa.Column("bbox_e", sa.Float(), nullable=True),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("nl_query", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("weight_preset", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lead_count", sa.Integer(), nullable=False),
        sa.Column("llm_pending", sa.Integer(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leads",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("search_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("osm_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("osm_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("normalized_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("street", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("housenumber", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("postcode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address_source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("normalized_domain", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "osm_tags", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("is_chain_suspected", sa.Boolean(), nullable=False),
        sa.Column("enrichment_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("llm_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["searches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("search_id", "osm_type", "osm_id", name="uq_lead_osm"),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_index("ix_leads_normalized_domain", ["normalized_domain"], unique=False)
        batch_op.create_index("ix_leads_search_id", ["search_id"], unique=False)

    op.create_table(
        "contacts",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lead_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("normalized_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verification_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("meta", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index("ix_contacts_lead_id", ["lead_id"], unique=False)

    op.create_table(
        "factor_scores",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lead_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("factor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("max_points", sa.Float(), nullable=False),
        sa.Column(
            "reasons", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lead_id", "factor", name="uq_factor_per_lead"),
    )
    with op.batch_alter_table("factor_scores", schema=None) as batch_op:
        batch_op.create_index("ix_factor_scores_lead_id", ["lead_id"], unique=False)

    op.create_table(
        "signals",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lead_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index("ix_signals_lead_key", ["lead_id", "key"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index("ix_signals_lead_key")

    op.drop_table("signals")
    with op.batch_alter_table("factor_scores", schema=None) as batch_op:
        batch_op.drop_index("ix_factor_scores_lead_id")

    op.drop_table("factor_scores")
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index("ix_contacts_lead_id")

    op.drop_table("contacts")
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index("ix_leads_search_id")
        batch_op.drop_index("ix_leads_normalized_domain")

    op.drop_table("leads")
    op.drop_table("searches")
    with op.batch_alter_table("overpass_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_overpass_cache_expires")

    op.drop_table("overpass_cache")
    op.drop_table("geocode_cache")
    with op.batch_alter_table("enrichment_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_enrichment_cache_expires")

    op.drop_table("enrichment_cache")
    # ### end Alembic commands ###
